### ISSUE TITLE
Setup ASAN, UBSAN, TSAN CI jobs

### ISSUE THREAD

**Issue by XVilka** [open-simh/simh#235]
Address sanitizer, UB (Undefined Behavior) sanitizer, Thread sanitizer will be helpful for catching obvious issues in the code while running tests.

Something like this could help:
```cmake
if(CMAKE_BUILD_TYPE MATCHES "Debug")
  add_compile_options(-fsanitize=address)
  add_compile_options(-fsanitize=undefined)
  add_link_options(-fsanitize=address)
  add_link_options(-fsanitize=undefined)
endif()
```

**Comment by bscottm** [comment]
For which compiler(s)?

**Comment by XVilka** [comment]
@bscottm from my experience both modern GCC and Clang work well with sanitizers, there are some differences but largely they overlap in reporting the same issues.

**Comment by bscottm** [comment]
I do think this is a good idea, with better scope

1.. Should this be done for any debug build or should sanitizers be run as separate rules in `build.yaml`?
2. Is there a simh project position on this proposal that guides (1)?

Scoping to GCC and Clang is easy by matching the CMake compiler ID, which exists in a couple of places already. All Debug vs. separate CI/CD builds has the potential for unexpected consequences (not counting the usual Pizz on things.)

**Comment by XVilka** [comment]
1. It's better to make it a separate job, from my experience, unless you have the reason to save CI workload/minutes
2. no idea

**Comment by bscottm** [comment]
@XVilka: I copied sanitizer support from `arsenm/sanitizers-cmake`, which supports GCC, Clang and MSVC. You will have to set the configuration option flags from the command line. These are summarized in `Sanitizers-README.md` (renamed `README.md` from `arsenm/santizers-cmake`.) The files are all licensed with the MIT license, so they ought to be compatible with `open-simh` and `simh`.

I had to tweak the code to ensure that sanitization is only added for Debug build configurations. And then did a test run on my RPi ARM64 with `-DSANITIZE_ADDRESS=On`, which failed for all of the right reasons. Excerpt from `simh-vax-780` test:

```
[ctest] =================================================================
[ctest] ==2060569==ERROR: LeakSanitizer: detected memory leaks
[ctest] 
[ctest] Direct leak of 677 byte(s) in 20 object(s) allocated from:
[ctest]     #0 0x7fb38f2e7c in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
[ctest]     #1 0x556ca30c00 in sim_exp_set ../../scp.c:13091
[ctest]     #2 0x556ca2f494 in sim_set_expect ../../scp.c:12937
[ctest]     #3 0x556c9f68d4 in expect_cmd ../../scp.c:5455
[ctest]     #4 0x556c9edce4 in do_cmd_label ../../scp.c:4210
[ctest]     #5 0x556c9f7ffc in call_cmd ../../scp.c:5630
[ctest]     #6 0x556c9edce4 in do_cmd_label ../../scp.c:4210
[ctest]     #7 0x556c9eba50 in do_cmd ../../scp.c:4034
[ctest]     #8 0x556c9e1ca4 in main ../../scp.c:2938
[ctest]     #9 0x7fb352ae14 in __libc_start_main ../csu/libc-start.c:308
[ctest]     #10 0x556c844594  (/mnt/bigyard/arm-twist/open-simh/BIN/vax780+0x104594)
[ctest] 
[ctest] Direct leak of 48 byte(s) in 4 object(s) allocated from:
[ctest]     #0 0x7fb38f2e7c in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
[ctest]     #1 0x556ca30c00 in sim_exp_set ../../scp.c:13091
[ctest]     #2 0x556ca2f494 in sim_set_expect ../../scp.c:12937
[ctest]     #3 0x556c9f68d4 in expect_cmd ../../scp.c:5455
[ctest]     #4 0x556c9edce4 in do_cmd_label ../../scp.c:4210
[ctest]     #5 0x556c9eba50 in do_cmd ../../scp.c:4034
[ctest]     #6 0x556c9e1ca4 in main ../../scp.c:2938
[ctest]     #7 0x7fb352ae14 in __libc_start_main ../csu/libc-start.c:308
[ctest]     #8 0x556c844594  (/mnt/bigyard/arm-twist/open-simh/BIN/vax780+0x104594)
[ctest] 
[ctest] SUMMARY: AddressSanitizer: 725 byte(s) leaked in 24 allocation(s).
```

There are a handful of simulators that currently fail (and I'm sorry to report, @sethm, 3b2 and 3b2-700 are in that list.) They all fail in `sim_exp_set` (`scp.c` line 13091).

I'm developing on the `cmake-sanitizer` branch in my `open-simh` fork. `cmake-sanitizer` is up-to-date with `open-simh/master`. I'll push to GH a little later on today or tomorrow.

**Comment by bscottm** [comment]
@sethm: 3b2 and 3b2-700 have a different address sanitizer output:

3b2:
```
=================================================================
==2057177==ERROR: AddressSanitizer: global-buffer-overflow on address 0x00558ea0ad68 at pc 0x00558e7f9024 bp 0x007ffc192960 sp 0x007ffc192978
READ of size 8 at 0x00558ea0ad68 thread T0
    #0 0x558e7f9020 in fix_writelock_mtab ../../scp.c:8067
    #1 0x558e7f81b4 in reset_all ../../scp.c:7951
    #2 0x558e7f8c30 in reset_all_p ../../scp.c:8030
    #3 0x558e7cf2b8 in main ../../scp.c:2871
    #4 0x7f9d19ae14 in __libc_start_main ../csu/libc-start.c:308
    #5 0x558e76b1b4  (/mnt/bigyard/arm-twist/open-simh/BIN/3b2+0x7b1b4)

0x00558ea0ad68 is located 16 bytes to the right of global variable 'iu_timer_mod' defined in '../../3B2/3b2_iu.c:277:6' (0x558ea0ad20) of size 56
0x00558ea0ad68 is located 24 bytes to the left of global variable 'iu_timer_reg' defined in '../../3B2/3b2_iu.c:282:5' (0x558ea0ad80) of size 208
SUMMARY: AddressSanitizer: global-buffer-overflow ../../scp.c:8067 in fix_writelock_mtab
Shadow bytes around the buggy address:
  0x001ab1d41550: 00 00 00 00 00 00 00 00 f9 f9 f9 f9 00 00 00 00
  0x001ab1d41560: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x001ab1d41570: 00 00 00 00 00 00 00 00 00 00 00 00 f9 f9 f9 f9
  0x001ab1d41580: 00 00 00 f9 f9 f9 f9 f9 00 00 00 00 00 00 00 00
  0x001ab1d41590: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x001ab1d415a0: f9 f9 f9 f9 00 00 00 00 00 00 00 f9 f9[f9]f9 f9
  0x001ab1d415b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x001ab1d415c0: 00 00 00 00 00 00 00 00 00 00 f9 f9 f9 f9 f9 f9
  0x001ab1d415d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x001ab1d415e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x001ab1d415f0: 00 00 00 f9 f9 f9 f9 f9 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==2057177==ABORTING
```

3b2-700:
```
=================================================================
==2057183==ERROR: AddressSanitizer: global-buffer-overflow on address 0x005584ee5388 at pc 0x005584cb7cf4 bp 0x007fd75cb300 sp 0x007fd75cb318
READ of size 8 at 0x005584ee5388 thread T0
    #0 0x5584cb7cf0 in fix_writelock_mtab ../../scp.c:8067
    #1 0x5584cb6e84 in reset_all ../../scp.c:7951
    #2 0x5584cb7900 in reset_all_p ../../scp.c:8030
    #3 0x5584c8df88 in main ../../scp.c:2871
    #4 0x7f8d57ce14 in __libc_start_main ../csu/libc-start.c:308
    #5 0x5584c1f304  (/mnt/bigyard/arm-twist/open-simh/BIN/3b2-700+0x7f304)

0x005584ee5388 is located 16 bytes to the right of global variable 'iu_timer_mod' defined in '../../3B2/3b2_iu.c:277:6' (0x5584ee5340) of size 56
0x005584ee5388 is located 24 bytes to the left of global variable 'iu_timer_reg' defined in '../../3B2/3b2_iu.c:282:5' (0x5584ee53a0) of size 208
SUMMARY: AddressSanitizer: global-buffer-overflow ../../scp.c:8067 in fix_writelock_mtab
Shadow bytes around the buggy address:
  0x001ab09dca20: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x001ab09dca30: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x001ab09dca40: f9 f9 f9 f9 00 00 00 f9 f9 f9 f9 f9 00 00 00 00
  0x001ab09dca50: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x001ab09dca60: 00 00 00 00 f9 f9 f9 f9 00 00 00 00 00 00 00 f9
=>0x001ab09dca70: f9[f9]f9 f9 00 00 00 00 00 00 00 00 00 00 00 00
  0x001ab09dca80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 f9 f9
  0x001ab09dca90: f9 f9 f9 f9 00 00 00 00 00 00 00 00 00 00 00 00
  0x001ab09dcaa0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x001ab09dcab0: 00 00 00 00 00 00 00 f9 f9 f9 f9 f9 00 00 00 00
  0x001ab09dcac0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==2057183==ABORTING

**Comment by sethm** [comment]
> ```
> [ctest] =================================================================
> [ctest] ==2060569==ERROR: LeakSanitizer: detected memory leaks
> [ctest] 
> [ctest] Direct leak of 677 byte(s) in 20 object(s) allocated from:
> [ctest]     #0 0x7fb38f2e7c in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
> [ctest]     #1 0x556ca30c00 in sim_exp_set ../../scp.c:13091
> [ctest]     #2 0x556ca2f494 in sim_set_expect ../../scp.c:12937
> [ctest]     #3 0x556c9f68d4 in expect_cmd ../../scp.c:5455
> [ctest]     #4 0x556c9edce4 in do_cmd_label ../../scp.c:4210
> [ctest]     #5 0x556c9f7ffc in call_cmd ../../scp.c:5630
> [ctest]     #6 0x556c9edce4 in do_cmd_label ../../scp.c:4210
> [ctest]     #7 0x556c9eba50 in do_cmd ../../scp.c:4034
> [ctest]     #8 0x556c9e1ca4 in main ../../scp.c:2938
> [ctest]     #9 0x7fb352ae14 in __libc_start_main ../csu/libc-start.c:308
> [ctest]     #10 0x556c844594  (/mnt/bigyard/arm-twist/open-simh/BIN/vax780+0x104594)
> [ctest] 
> [ctest] Direct leak of 48 byte(s) in 4 object(s) allocated from:
> [ctest]     #0 0x7fb38f2e7c in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
> [ctest]     #1 0x556ca30c00 in sim_exp_set ../../scp.c:13091
> [ctest]     #2 0x556ca2f494 in sim_set_expect ../../scp.c:12937
> [ctest]     #3 0x556c9f68d4 in expect_cmd ../../scp.c:5455
> [ctest]     #4 0x556c9edce4 in do_cmd_label ../../scp.c:4210
> [ctest]     #5 0x556c9eba50 in do_cmd ../../scp.c:4034
> [ctest]     #6 0x556c9e1ca4 in main ../../scp.c:2938
> [ctest]     #7 0x7fb352ae14 in __libc_start_main ../csu/libc-start.c:308
> [ctest]     #8 0x556c844594  (/mnt/bigyard/arm-twist/open-simh/BIN/vax780+0x104594)
> [ctest] 
> [ctest] SUMMARY: AddressSanitizer: 725 byte(s) leaked in 24 allocation(s).
> ```

This looks like a bug in `scp.c`. `ep->match_pattern` is allocated on line 13091, but then again on line 13122. It is not freed between these two allocations.

Meanwhile, both of the 3B2 bugs...

> ```
> ...
> 0x005584ee5388 is located 16 bytes to the right of global variable 'iu_timer_mod' defined in '../../3B2/3b2_iu.c:277:6' (0x5584ee5340) of size 56
> 0x005584ee5388 is located 24 bytes to the left of global variable 'iu_timer_reg' defined in '../../3B2/3b2_iu.c:282:5' (0x5584ee53a0) of size 208
> ...
> ```

Both the 3B2/400 and 3B2/700 have the same bug -- the `iu_timer_mod` array is not null-terminated, but should be. It looks like the `contty_mod` is also not null terminated, but should be, I'm surprised the sanitizer didn't pick that up too (or maybe it did on another pass?) Anyway, both of those will need to be fixed.
